# Details
mod_author=Luken
mod_name=Ping Wheel
mod_id=pingwheel
archive_name=Ping-Wheel
contributors=RXJpaw
license=MIT
description=Mark locations similar to the ping mechanism found in modern co-op multiplayer games.
link_home=https://www.curseforge.com/minecraft/mc-mods/ping-wheel
link_src=https://github.com/LukenSkyne/Minecraft-Ping-Wheel
link_issues=https://github.com/LukenSkyne/Minecraft-Ping-Wheel/issues

# Common
mod_version=1.12.1

# Minecraft
minecraft_version=1.21.1
java_version=21

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430

# ModDevGradle
# https://projects.neoforged.net/neoforged/moddevgradle
mod_dev_gradle_version=2.0.115

# ParchmentMC
# https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_minecraft=1.21
parchment_version=2024.07.28

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.102.1+1.21.1
fabric_loader_version=0.15.11
fabric_compatible_range=>=1.21 <=1.21.1
loom_version=1.11-SNAPSHOT

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=52.0.2
forge_loader_version=52
forge_compatible_range=[1.21,1.21.1]

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.0.143
neoforge_loader_version=1
neoforge_compatible_range=[1.21,1.21.1]

# Integrations
distanthorizons_api_version=5.1.0
voicechat_api_version=2.6.0
ftbteams_version=6930910
sable_version=1.6.0

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
