# Details
mod_author=Luken
mod_name=Ping Wheel
mod_id=pingwheel
archive_name=Ping-Wheel
contributors=RXJpaw
license=MIT
description=Mark locations similar to the ping mechanism found in modern co-op multiplayer games.
link_home=https://www.curseforge.com/minecraft/mc-mods/ping-wheel
link_src=https://github.com/LukenSkyne/Minecraft-Ping-Wheel
link_issues=https://github.com/LukenSkyne/Minecraft-Ping-Wheel/issues

# Common
mod_version=1.12.1

# Minecraft
minecraft_version=1.19.3
java_version=17

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.76.1+1.19.3
fabric_loader_version=0.14.21
fabric_compatible_range=1.19.3
loom_version=1.9-SNAPSHOT

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=44.1.0
forge_loader_version=44
forge_compatible_range=[1.19.3]

# Integrations
distanthorizons_api_version=5.1.0
voicechat_api_version=2.6.0
ftbteams_version=4611938

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
