# Details
mod_author=Luken
mod_name=Ping Wheel
mod_id=pingwheel
archive_name=Ping-Wheel
contributors=RXJpaw
license=MIT
description=Mark locations similar to the ping mechanism found in modern co-op multiplayer games.
link_home=https://www.curseforge.com/minecraft/mc-mods/ping-wheel
link_src=https://github.com/LukenSkyne/Minecraft-Ping-Wheel
link_issues=https://github.com/LukenSkyne/Minecraft-Ping-Wheel/issues

# Common
mod_version=1.12.0
minecraft_version=1.21.8
java_version=21

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.8-20250717.133445

# ModDevGradle
# https://projects.neoforged.net/neoforged/moddevgradle
mod_dev_gradle_version=2.0.115

# ParchmentMC
# https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_minecraft=1.21.8
parchment_version=2025.09.14

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.129.0+1.21.8
fabric_loader_version=0.16.14
fabric_compatible_range=>=1.21.6 <=1.21.8
loom_version=1.11-SNAPSHOT

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=58.0.0
forge_loader_version=56
forge_compatible_range=[1.21.6,1.21.8]

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.7.1-beta
neoforge_loader_version=1
neoforge_compatible_range=[1.21.7,1.21.8]

# Integrations
distanthorizons_api_version=4.0.0
voicechat_api_version=2.6.0
ftbteams_version=6930910

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
