blank_issues_enabled: false

contact_links:
  - name: ? Questions & Discussions
    url: https://github.com/a-Void-Deer/Minecraft-Ping-For-It/discussions
    about: You can ask questions or discuss Ping For It here instead of opening an issue.